name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u ayushm98 --password-stdin
          docker build -t ghcr.io/ayushm98/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/ayushm98/arithmetic-service:latest
